"""The two console entry points, and the constraint they both enforce.

M4 requires that every table is regenerated by one command, so ``meddial-tables``
has to work on the records ``meddial-run`` writes without a hand-editing step in
between. C2 requires that neither command writes restricted-derived output into
the working tree by accident.

``meddial-run`` builds local providers and is therefore not exercised end to end
here -- that needs a running Ollama, which CI does not have and
MEDDIAL_DISABLE_EXTERNAL_CALLS forbids. Its argument parsing and its refusal
paths are covered; its provider construction is not.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from meddial.cli import _read_cases, check_output_location, run_main, tables_main
from meddial.evaluation import ReferenceMode
from meddial.experiments import (
    ExperimentRunner,
    MedDialBackend,
    ModelSpec,
    RunConfig,
)
from meddial.llm import MockProvider

DIALOGUE_JSON = (
    '{"dialogue": [{"role": "Doctor", "text": "What brings you in today?"}, '
    '{"role": "Patient", "text": "I have been short of breath."}]}'
)


def _config() -> RunConfig:
    digest = "sha256:" + "a" * 64
    return RunConfig(
        name="cli-test",
        variant="direct_llm",
        patient_policy_id="FULL",
        patient_policy_version="2.0",
        doctor_guidance_id="FULL",
        reference_mode=ReferenceMode.FULL_REFERENCE,
        seed=7,
        max_turns=2,
        max_attempts=1,
        thresholds={"naturalness": 0.6},
        models={"judge": ModelSpec("judge-model", digest, "qwen", "Q4_K_M")},
        prompt_versions={"patient": "sha256:patient"},
    )


# -- C2 ---------------------------------------------------------------------


def test_output_inside_the_repository_is_refused() -> None:
    """Every file these commands write is derived from restricted data."""
    with pytest.raises(SystemExit, match="inside the repository"):
        check_output_location(Path(__file__).parent, allowed=False)


def test_the_in_repo_refusal_can_be_overridden_deliberately() -> None:
    """Refusing outright would block a legitimate synthetic-only run."""
    check_output_location(Path(__file__).parent, allowed=True)


def test_output_outside_the_repository_is_allowed(tmp_path: Path) -> None:
    check_output_location(tmp_path / "out", allowed=False)


# -- case reading -----------------------------------------------------------


def test_cases_are_read_one_json_object_per_line(tmp_path: Path) -> None:
    path = tmp_path / "cases.jsonl"
    path.write_text('{"case_id": "case-1"}\n\n{"case_id": "case-2"}\n', encoding="utf-8")

    assert [case["case_id"] for case in _read_cases(path)] == ["case-1", "case-2"]


def test_a_malformed_case_line_names_its_line_number(tmp_path: Path) -> None:
    path = tmp_path / "cases.jsonl"
    path.write_text('{"case_id": "case-1"}\nnot json\n', encoding="utf-8")

    with pytest.raises(SystemExit, match="cases.jsonl:2"):
        _read_cases(path)


def test_an_empty_case_file_is_refused(tmp_path: Path) -> None:
    path = tmp_path / "cases.jsonl"
    path.write_text("\n\n", encoding="utf-8")

    with pytest.raises(SystemExit, match="holds no cases"):
        _read_cases(path)


# -- meddial-run refusals ---------------------------------------------------


def test_run_refuses_an_unparseable_config(tmp_path: Path) -> None:
    config = tmp_path / "config.json"
    config.write_text("{not json", encoding="utf-8")
    cases = tmp_path / "cases.jsonl"
    cases.write_text('{"case_id": "case-1"}\n', encoding="utf-8")

    with pytest.raises(SystemExit, match="Config error"):
        run_main(
            [
                "--config", str(config),
                "--cases", str(cases),
                "--out", str(tmp_path / "out"),
            ]
        )


def test_run_reads_the_config_before_it_builds_a_provider(tmp_path: Path) -> None:
    """A typo in the variant name must not wait on model loading to surface."""
    config = tmp_path / "config.json"
    config.write_text(json.dumps({"name": "x", "variant": "no_such"}), encoding="utf-8")
    cases = tmp_path / "cases.jsonl"
    cases.write_text('{"case_id": "case-1"}\n', encoding="utf-8")

    with pytest.raises(SystemExit, match="Config error"):
        run_main(
            [
                "--config", str(config),
                "--cases", str(cases),
                "--out", str(tmp_path / "out"),
            ]
        )


# -- one command regenerates every table ------------------------------------


def test_tables_regenerates_every_output_from_the_records_a_run_wrote(
    tmp_path: Path, capsys
) -> None:
    """M4's "every table regenerated by one command", against real records."""
    runner = ExperimentRunner(tmp_path / "runs-root", git_commit="abc123")
    result = runner.run(
        _config(),
        [{"case_id": "case-1", "note_text": "Patient reports dyspnoea."}],
        MedDialBackend(generator=MockProvider([DIALOGUE_JSON]), judge=MockProvider()),
    )

    exit_code = tables_main(
        [
            "--attempts", str(result.context.attempts_path),
            "--out", str(tmp_path / "tables"),
        ]
    )

    assert exit_code == 0
    written = {path.name for path in (tmp_path / "tables").rglob("*") if path.is_file()}
    assert {"scores.csv", "acceptance.csv", "cost.csv", "primary_metric.svg"} <= written
    assert "analysis_manifest.json" in written, "an analysis must say how it was made"
    assert "Read 1 attempt record" in capsys.readouterr().out
